---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: install qemu-guest agent latest version
    apt:
      name: qemu-guest-agent
      state: latest

  - name: install python latest version
    apt:
      name: python3
      state: latest
